### ISSUE TITLE
Can't use with babel-preset-env

### ISSUE THREAD

**Issue by jmorino** [r-murphy/babel-plugin-transform-modules-ui5#1]
When using with `babel-preset-env` and `babel-plugin-syntax-class-properties`, the transpiling operation fails:
- if using class properties, Babel returns the following error message : 
  > Missing class properties transform
- otherwise, UI5 classes are still transpiled as if they were standard JS classes

.babelrc :
```json
{
	"sourceMaps" : true,
	"minified" : false,
	"presets" : [
		["env", {
			"debug": true,
			"modules" : false
		}]
	],
	"plugins" : ["syntax-class-properties","transform-modules-ui5"]
}
```

**Comment by jmorino** [comment]
There seems to be a problem with the order the plugins are called, ie. AFTER the preset's plugins. Thus, the `syntax-class-properties` plugin doesn't bring support for class properties, and UI5 classes are not transpiled when the `transform-es2015-classes` plugin is called.

Nevertheless, this should work as stated by [Babel documentation](https://babeljs.io/docs/plugins/#plugin-preset-ordering):
>Ordering matters for each visitor in the plugin.
>
>This means if two transforms both visit the “Program” node, the transforms will run in either plugin or preset order.
>
>Plugins run before Presets.
>Plugin ordering is first to last.
>Preset ordering is reversed (last to first).

**Comment by r-murphy** [comment]
@jmorino I think I've fixed this issue. Please give it a try. 

I learned something new about babel plugins ordering and visitors. I had the logic in Program.exit visitor (for no good reason) rather than in Program.enter or directly in Program. So even though this plugin might run before tranform-es2015-classes for a given visitor, the Program.exit is visited after that plugin has already done all of its transformations (in Program).

Here's a good reference.
http://thejameskyle.com/babel-plugin-ordering.html

I hope this helps and thanks again for raising it. This motivated me to finally start on my own example projects (js and ts versions) so hopefully that will avoid these issues for grunt/gulp builds (my own use is a custom node module calling babel core APIs directly).

**Comment by jmorino** [comment]
@r-murphy yes, it works! Thanks a lot!

I had to do the same: a custom grunt plugin calling babel APIs in 2 steps ([my plugin is here](https://github.com/jmorino/grunt-openui5-babel)). But now I can go back to a normal babel task.
