### ISSUE TITLE
'export type' being transpiled

### ISSUE THREAD

**Issue by lucasheim** [r-murphy/babel-plugin-transform-modules-ui5#26]
When I write a typescript file like this:

```typescript
export type testType = string | boolean;

export class testClass {
  public testMethod() {
    console.log("test");
  }
}
```
And run it using babel's typescript-preset, it transpiles to this:

```javascript
export class testClass {
  testMethod() {
    console.log("test");
  }

}
```
As the type is something only important to Typescript, it shouldn't be transpiled. But, when I go through typescript-preset and then through transform-modules-ui5, this is the result:

```javascript
sap.ui.define([], function () {
  class testClass {
    testMethod() {
      console.log("test");
    }

  }

  var __exports = {
    __esModule: true
  };
  __exports.testType = testType;
  __exports.testClass = testClass;
  return __exports;
});
```

The type ends up being transpiled: `__exports.testType = testType;`, even though it's not on Typescript's transpiling. Maybe there's a need to test the exports of a file before outputting them to JS, as `testType` ends up having no reference in the file and we get a runtime error.

I have an example on this repo: https://github.com/lucasheim/transform-ui5-playground

**Comment by Elberet** [comment]
I believe this issue is, by and large, caused by improper sequencing of the plugin's visitors (similar in spirit to the root cause of #23).

The module wrapper [visits `ExportNamedDeclaration` nodes](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/modules/visitor.js#L154) first and [replaces them with their declaration part](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/modules/visitor.js#L209).

Then, much, much later, [it builds the `sap.ui.define` wrapper](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/index.js#L55) based on the export declarations it has removed previously, even if another plugin has removed the remaining declaration in the meantime.

Testing whether the to-be-exported identifier still exists within the file's scope might be possible, but it's IMO a bandaid for a deeper design problem. The `ExportNamedDeclaration` handler and its siblings should be moved to a nested `traverse` call in the `Program` exit handler.
