### ISSUE TITLE
Only convert ES classes into Control.extend(..) syntax when controller.js suffix is used

### ISSUE THREAD

**Issue by o0Djeen0o** [r-murphy/babel-plugin-transform-modules-ui5#7]
Right now, the default behavior is that every class with `extends` property is converted to a  
`Control.extend(...)` syntax for UI5 compatibility.

From my understanding : 
* `Control.extend(...)` is a mechanism dedicated to UI controls.
* A controller __by convention__ from UI5 is suffixed by `.controller.js`
* a `@nonui5` annotation has to be used to keep classical `extends` usage.

My proposal would be to use a __by default__ convention where : 
* all js files with suffix `.controller.js` with `extends` have to be converted to UI5 syntax
* all other files must be kept as it, as they probably aren't controllers.

Maybe there is a good reason why you choosed to use your plugin like that ? @r-murphy Thanks for the great work, it is really valuable, especially in conjunction with Typescript !

**Comment by r-murphy** [comment]
That's an interesting proposal, because I'm also not a fan of the `@nonui5` annotation and it feels like a hack (so it probably is).

In our code base, we also have custom controls written as ES classes, and also some models which extend from JSONModel, which is why I originally set the defaults the way they are. However we always add the `@name` annotation, so we set the `onlyConvertNamedClass` option to true, and then never need `@nonui5`.

I'm hesitant to change the default behaviour in v6 but I could change it in v7 (babel core is getting close to v7). In the meantime, I could add an option to provide the behaviour you're looking for. Something like `onlyConvertAnnotatedOrControllerClasses`. Or if you're already annotating controllers with @name then maybe the existing option is sufficient for now?

Also, I'm glad you like the plugin.

**Comment by o0Djeen0o** [comment]
I think that existing option is sufficient for now, no need to change it in a hurry ;-) There is no limitation, so not an issue to keep it like that for some time.

Thanks!

**Comment by r-murphy** [comment]
7.0.0 has support for `.controller.js` classes, and still has the `onlyConvertNamedClass` option, so I'm going to close this since I think the plugin scope shouldn't be limited to controller, and I think there are sufficient options to customize the behaviour.
