### ISSUE TITLE
Issues with multiple exports where some definitions have been cleaned by other plugins

### ISSUE THREAD

**Issue by o0Djeen0o** [r-murphy/babel-plugin-transform-modules-ui5#9]
Context:

I'm using this plugin with https://babeljs.io/docs/en/babel-preset-typescript preset, writing code in Typescript. My configuration is using two presets : 
1. the typescript preset in order to convert our typescript code into javascript code
2. Your plugin, encapsulated into a preset in order to be ran after typescript preset.

I was forced to do so, otherwise some dependencies/exports were not properly removed (i.e. interfaces were removed from files but still imported) as the typescript preset is no more able to shake tree if sap.require transformations already occurred.

Issue with exports :
This plugin does not seem to take into account previously removed exports. Let's take an example : 

Initial Example.ts file
```
export const MY_CONSTANT = "constant";
export interface IMyInterface { id: string; }
```

If using the typescript preset only, the output Example.js file should look like  : 
```
export const MY_CONSTANT = "constant";
```
Interface is removed, because it has no meaning in Javascript code.

But, if using typescript preset, then your plugin, the output would look like : 
```
sap.ui.define([], function () {
  const MY_CONSTANT = "constant";
  const __exports = {
    __esModule: true
  };
  __exports.MY_CONSTANT = MY_CONSTANT ;
  __exports.IMyInterface = IMyInterface ;
  return __exports;
});
```

The interface exports is restored, but no definition of the interface can be found. Is there any way in Babel from your plugin to check that a expression has been removed by another plugin prior to export step ? I'm still really novice with Babel plugin mechanism, so hard to find easy answer here.

Thanks for your help !

**Comment by r-murphy** [comment]
Unfortunately, this is a bigger issue than just the `export interface`. The 2 plugins are don't seem not compatible for class conversion as well when the class uses certain typescript feature like generics. 

I'll try to handle this case as a 1-off, but getting full compatibility may require re-architecting this plugin.

This is due to babel visitors and when each plugin gets called. Babel doesn't simply just call one plugin to do all its work and then the next plugin to do all its work.
Instead, babel parses the file to generate the AST and then calls the plugins in order for each 'visitor'. My plugin currently does all of its work in the `Program` visitor, which is the first one. The typescript plugin does some of its work in the `Program` visitor, like handling imports. But it does some other work like export interface erasure and generic erasure in later, more specific visitors (Class, Export) that are called after the Program visitor. 

The reason I do all my work in the Program visitor is to ensure that the UI5 work in done before some other class related plugins from preset-env that may also do work in the Program visitor. So any changes to re-architect the plugin to use different visitors need to ensure compatibility with other class conversion plugins.

Ideally the Typescript plugin would just do all its work in the Program visitor to avoid this situation.

I'll do some more investigation to see what's possible to fully resolve this.

**Comment by o0Djeen0o** [comment]
@r-murphy Also another side effect probably related : 

When defining a class member without a value :

```
import BaseController from "./Base.controller";

export default class Test extends BaseController {

    private mParameter: string | undefined;
}
```

preset Typescript will remove the member definition

```
import BaseController from "./Base.controller";
export default class Test extends BaseController {
}
```

But then `babel-plugin-transform-modules-ui5` will try to convert it, leading to an exception : 
```
TypeError: Property value of ObjectProperty expected node to be of a type ["Expression","Pattern","RestElement"] but instead got null
```

**Comment by o0Djeen0o** [comment]
Hello @r-murphy, 

Sorry for the long delay. So far I wasn't able to work with latest `7.0.0-rc.1` version. I have an issue with classes which are no more converted.

A class (I tried with the simplest javascript file to test, `Test.js`, without Typescript), which had an output in `6.18.1` like :

```
sap.ui.define(["sap/ui/core/UIComponent"], function (UIComponent) {
  const Component = UIComponent.extend("truc.test.Component", {});
});
```
now outputs to:

```
sap.ui.define(["sap/ui/core/UIComponent"], function (UIComponent) {
  /**
   * @namespace truc.test
   * @controller
   */
  class Component extends UIComponent {}
});
```

If suffix `controller.js` is used, then output is back to normal, but `@controller` annotation seems to have no effect. For files like `Component.js`, this is a real issue.

Have you any idea of what could go wrong ?

**Comment by o0Djeen0o** [comment]
@r-murphy Just tested with
```
/**
   * @name app.Truc
   * @controller
   */
```
And the output is ok again. So the issue seems to be with `@namespace` property no more used to convert a class

**Comment by r-murphy** [comment]
Hi @o0Djeen0o . Thanks for trying out v7 and raising that issue. I created issue #12 for that and fixed it.

**Comment by o0Djeen0o** [comment]
@r-murphy Thanks for the quick fix ! rc.2 is not yet available on npm, are you planning to publish it soon ?

**Comment by r-murphy** [comment]
@o0Djeen0o  Sorry I missed that step. It's published now.

**Comment by o0Djeen0o** [comment]
Hi @r-murphy,

I've finally had time to upgrade to latest preset versions (`@babel/preset-typescript 7.3.3` and `babel-preset-transform-ui5 7.0.0-rc.7`) (previously I still had some issues with code generations, probably your changes made some nice improvements here), for now outputted code seems great ! I'll make some additional tests and get back to you.

Thanks for all your hard work !

**Comment by r-murphy** [comment]
@o0Djeen0o I'm going to close this for now since 7.0.0 handles the typescript cases I'm aware of. Feel free to reopen or log a new one if you encounter a new issue. I'm still not personally using the babel typescript plugin or preset (still using tsc and then babel).
